/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/prasad89/devspace-operator/pkg/apis/platform.devspace.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDevSpaceSpecs implements DevSpaceSpecInterface
type FakeDevSpaceSpecs struct {
	Fake *FakePlatformV1alpha1
	ns   string
}

var devspacespecsResource = schema.GroupVersionResource{Group: "platform.devspace.io", Version: "v1alpha1", Resource: "devspacespecs"}

var devspacespecsKind = schema.GroupVersionKind{Group: "platform.devspace.io", Version: "v1alpha1", Kind: "DevSpaceSpec"}

// Get takes name of the devSpaceSpec, and returns the corresponding devSpaceSpec object, and an error if there is any.
func (c *FakeDevSpaceSpecs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DevSpaceSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(devspacespecsResource, c.ns, name), &v1alpha1.DevSpaceSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DevSpaceSpec), err
}

// List takes label and field selectors, and returns the list of DevSpaceSpecs that match those selectors.
func (c *FakeDevSpaceSpecs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DevSpaceSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(devspacespecsResource, devspacespecsKind, c.ns, opts), &v1alpha1.DevSpaceSpecList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DevSpaceSpecList), err
}

// Watch returns a watch.Interface that watches the requested devSpaceSpecs.
func (c *FakeDevSpaceSpecs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(devspacespecsResource, c.ns, opts))

}

// Create takes the representation of a devSpaceSpec and creates it.  Returns the server's representation of the devSpaceSpec, and an error, if there is any.
func (c *FakeDevSpaceSpecs) Create(ctx context.Context, devSpaceSpec *v1alpha1.DevSpaceSpec, opts v1.CreateOptions) (result *v1alpha1.DevSpaceSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(devspacespecsResource, c.ns, devSpaceSpec), &v1alpha1.DevSpaceSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DevSpaceSpec), err
}

// Update takes the representation of a devSpaceSpec and updates it. Returns the server's representation of the devSpaceSpec, and an error, if there is any.
func (c *FakeDevSpaceSpecs) Update(ctx context.Context, devSpaceSpec *v1alpha1.DevSpaceSpec, opts v1.UpdateOptions) (result *v1alpha1.DevSpaceSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(devspacespecsResource, c.ns, devSpaceSpec), &v1alpha1.DevSpaceSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DevSpaceSpec), err
}

// Delete takes name of the devSpaceSpec and deletes it. Returns an error if one occurs.
func (c *FakeDevSpaceSpecs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(devspacespecsResource, c.ns, name), &v1alpha1.DevSpaceSpec{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDevSpaceSpecs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(devspacespecsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DevSpaceSpecList{})
	return err
}

// Patch applies the patch and returns the patched devSpaceSpec.
func (c *FakeDevSpaceSpecs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DevSpaceSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(devspacespecsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DevSpaceSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DevSpaceSpec), err
}
