---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.devspace.io
  resources:
  - devspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.devspace.io
  resources:
  - devspaces/finalizers
  verbs:
  - update
- apiGroups:
  - platform.devspace.io
  resources:
  - devspaces/status
  verbs:
  - get
  - patch
  - update
